services:
  jekyll:
    image: amirpourmand/al-folio
    #build: .
    #command: bundle install && bundle exec jekyll serve --host 0.0.0.0
    ports:
      - 8080:8080
    volumes:
      - .:/srv/jekyll
